version: '0.0.1'

services:
  frontend:
    image: fors1de/frontend-dev
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./frontend:/app
  backend:
    image: fors1de/backend-dev
    restart: always
    ports:
      - '5000:5000'
    volumes:
      - /backend/node_modules
      - ./backend:/app
